-- ==========================================
-- SETUP SYSTEM CONFIGS TABLE
-- ==========================================

-- 1. Create table if not exists
CREATE TABLE IF NOT EXISTS system_configs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_key TEXT UNIQUE NOT NULL,
    config_value TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Enable RLS
ALTER TABLE system_configs ENABLE ROW LEVEL SECURITY;

-- 3. Policies
-- Public Read: Allow app to read configs (or restrict to auth if sensitive, but prices usually public)
CREATE POLICY "Public Read Configs" ON system_configs FOR SELECT TO public USING (true);
-- Admin Write: Only admins
-- (Assuming you manually edit or have admin UI, strict policy for now)
DROP POLICY IF EXISTS "Admin Full Access Configs" ON system_configs;
-- For now, allow auth write or stick to SQL Editor management to be safe.
-- CREATE POLICY "Admin Write Configs" ...

-- 4. Seed Data (Upsert)
insert into system_configs (config_key, config_value, description)
values 
  ('v2', '1', 'Credit cost for Standard Model (Flash)'),
  ('v3', '2', 'Credit cost for Pro Model')
on conflict (config_key) do update 
set config_value = excluded.config_value;
