import { NextResponse } from 'next/server';
import { sql } from '@/lib/postgres/client';

export async function GET() {
    try {
        console.log('Checking generation_history schema...');

        // 0. Ensure Gallery Tables Exist
        await sql`
            CREATE TABLE IF NOT EXISTS user_gallery (
                id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
                user_id uuid NOT NULL,
                image_url text NOT NULL,
                thumbnail_url text,
                metadata jsonb DEFAULT '{}'::jsonb,
                created_at timestamp with time zone DEFAULT NOW()
            )
        `;
        await sql`
            CREATE TABLE IF NOT EXISTS guest_gallery (
                id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
                guest_id text NOT NULL,
                image_url text NOT NULL,
                thumbnail_url text,
                metadata jsonb DEFAULT '{}'::jsonb,
                created_at timestamp with time zone DEFAULT NOW()
            )
        `;

        // 1. Check column type
        const cols = await sql`
            SELECT data_type 
            FROM information_schema.columns 
            WHERE table_name = 'generation_history' 
            AND column_name = 'history_id'
        `;

        if (cols.length === 0) return NextResponse.json({ error: 'Column history_id not found' });

        const type = cols[0].data_type;
        console.log('History ID Type:', type);

        // 2. Apply fix based on type
        if (type === 'integer' || type === 'bigint') {
            console.log('Applying Integer Identity Fix...');
            // Check if it already has a sequence?
            // Just try adding identity, if it fails "already exists", ignore
            try {
                await sql`ALTER TABLE generation_history ALTER COLUMN history_id ADD GENERATED BY DEFAULT AS IDENTITY`;
                return NextResponse.json({ success: true, message: 'Fixed: Added IDENTITY to integer/bigint' });
            } catch (err: any) {
                // Determine if it failed because it's already an identity or not null issue?
                // If it failed because "column is not null" or similar, we might need a sequence.
                // Fallback to creating a sequence manually if identity fails?
                // Actually the error is "null value in column...", so it HAS no default.
                // Maybe it's not a primary key?
                console.error('Identity fix error:', err);

                // Fallback: Create sequence manually
                await sql`CREATE SEQUENCE IF NOT EXISTS generation_history_id_seq`;
                await sql`ALTER TABLE generation_history ALTER COLUMN history_id SET DEFAULT nextval('generation_history_id_seq')`;
                return NextResponse.json({ success: true, message: 'Fixed: Added SEQUENCE default' });
            }
        } else if (type === 'uuid') {
            console.log('Applying UUID Fix...');
            await sql`ALTER TABLE generation_history ALTER COLUMN history_id SET DEFAULT gen_random_uuid()`;
            return NextResponse.json({ success: true, message: 'Fixed: Added UUID default' });
        } else if (type === 'text') {
            // If it's text, maybe specific ID or uuid
            await sql`ALTER TABLE generation_history ALTER COLUMN history_id SET DEFAULT gen_random_uuid()::text`;
            return NextResponse.json({ success: true, message: 'Fixed: Added UUID::text default' });
        }

        return NextResponse.json({ message: `Unknown type: ${type}, no fix applied` });
    } catch (e: any) {
        console.error('Fix DB Error:', e);
        return NextResponse.json({ error: e.message });
    }
}
